### ISSUE TITLE
update for 7002520 possible?

### ISSUE THREAD

**Issue by arpu** [andreafabrizi/BresserWeatherCenter#1]
i have the newer version 
https://www.bresser.de/en/Weather-Time/7002520000000.html

but it looks like the communication has changed
i haved logged some packages, but i have no idea how to decode this 
[log.txt](https://github.com/andreafabrizi/BresserWeatherCenter/files/2000944/log.txt)

if anyone have some idea, this would be awesome

**Comment by andreafabrizi** [comment]
@arpu, I advise you to take a look at this project https://github.com/jopohl/urh
It's very useful for analyse unknown wireless protocols.
